# Generated by Django 3.2.2 on 2021-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
