# Generated by Django 3.2.2 on 2021-07-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210726_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
