# Generated by Django 3.2.2 on 2021-07-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='status',
        ),
    ]
