# Generated by Django 3.2.2 on 2022-03-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210726_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='city',
            field=models.CharField(default='dehradun', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
